# require_relative '../node_modules/react-native/scripts/react_native_pods'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# platform :ios, '12.4'
# install! 'cocoapods', :deterministic_uuids => false

# production = ENV["PRODUCTION"] == "1"

# target 'mytheresa' do
#   config = use_native_modules!

#   # Flags change depending on the env values.
#   flags = get_default_flags()

#   use_react_native!(
#     :path => config[:reactNativePath],
#     # to enable hermes on iOS, change `false` to `true` and then install pods
#     :production => production,
#     :hermes_enabled => flags[:hermes_enabled],
#     :fabric_enabled => flags[:fabric_enabled],
#     :flipper_configuration => FlipperConfiguration.enabled,
#     # An absolute path to your application root.
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )

#   target 'mytheresaTests' do
#     inherit! :complete
#     # Pods for testing
#   end

#   post_install do |installer|
#     react_native_post_install(installer)
#     __apply_Xcode_12_5_M1_post_install_workaround(installer)
#   end
# end


require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'mytheresa' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  target 'mytheresaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
